#!/bin/env sh

make clean

find . -name *~	-exec rm  {} \;
find . -name *.bak	-exec rm  {} \;
find . -name \#*	-exec rm {} \;
find . -name Makefile -exec rm {} \;

rm -f config.{status,h,log}
rm -f intltool-*
rm -f TODO.tasks
rm -rf Debug
rm -rf autom4te.cache

echo The end
